#####################################################################
# Update and configure base ubuntu server for laradock
#####################################################################

- name: Install Python libs
  apt: 
    update_cache: yes
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg
    
- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: codename == 'buster'

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  when: codename == 'bionic'


- name: add docker to repo (ubuntu 18-04 bionic)
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  when: codename == 'bionic'
  
- name: add docker to repo
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: codename == 'buster'

- name: change acl
  ansible.builtin.file:
    path:  /usr/share/keyrings/docker-archive-keyring.gpg
    mode: a+r 

- name: install docker-ce
  apt: 
    update_cache: yes
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

- name: Modify privilege
  become: true
  shell: usermod -aG docker $USER

- name: Change privilege of docker
  become: true
  command: chmod +x /usr/bin/docker  
  
- name: Update Python libraries
  pip:
    name: 
      - docker
      - docker-compose


- name: Install Docker Compose
  raw: curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Make Docker Compose Executable
  file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0755'
