---
- hosts: staging
  become: true
  gather_facts: no
  become_method: sudo
#  vars_files:
#    - ansible-variables.yml
  tasks:
    - import_role:
        name: initial-setup

    
    - import_role:
        name: dunkomatic
      when: dunkomatic|default(False)|bool == True
