#####################################################################
# Update and configure base ubuntu server for laradock
#####################################################################

- name: Get OS release
  raw: lsb_release -c
  register: lsb_release

- name: Update apt cache
  raw: apt-get -y update

- name: If needed, install Python
  raw: apt-get -y install python3 python3-pip 

- name: Set Hostname
  hostname:
    name: "{{hostname}}"

- name: Gather Facts
  setup:

- name: Add hostname to hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ advertise_address|default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }} {{hostname}}"
    state: present
